### ISSUE TITLE
File missing - "log_testset.txt"

### ISSUE THREAD

**Issue by Fuann** [key2miao/TSTNN#2]
https://github.com/key2miao/TSTNN/blob/3a1dac4968bdb45d959985c535ab359f3f3cc4ce/gen_pair.py#L62-L64

Hi, I follow the code and try to generate the training data by "gen_pair.py",
but there is a file missing that cannot go further. Is there something I missed in the preprocessing ?

Thanks !

**Comment by key2miao** [comment]
> https://github.com/key2miao/TSTNN/blob/3a1dac4968bdb45d959985c535ab359f3f3cc4ce/gen_pair.py#L62-L64
> 
> Hi, I follow the code and try to generate the training data by "gen_pair.py",
> but there is a file missing that cannot go further. Is there something I missed in the preprocessing ?
> 
> Thanks !

Hi, thank you for question, you can find that file in website of Voice Bank dataset.

**Comment by Fuann** [comment]
Fix it !
